//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiretreeAssessment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Listing
    {
        [Key]
        public int ListingId { get; set; }

        [Required, Display(Name = "Upload image")]
        public string ImagePath { get; set; }

        [Required, Display(Name = "Image")]
        public HttpPostedFileBase ImageFile { get; set; }

        [Required, Display(Name = "Price")]
        public double Price { get; set; }

        [Required, Display(Name = "No. of Bedrooms")]
        public int Bedrooms { get; set; }

        [Required, Display(Name = "Reference Number")]
        public int RefNumber { get; set; }

        [Required, Display(Name = "Marketing Heading")]
        public string MarketingHeading { get; set; }

        [Required, Display(Name = "Description")]
        public string Description { get; set; }

        [Required, Display(Name = "Suburb")]
        public string Suburb { get; set; }

        [ForeignKey("Agent")]
        [Required, Display(Name = "Agent")]
        public Nullable<int> AgentId { get; set; }
        public virtual Agent Agent { get; set; }
        
        [Display(Name = "Agent's Email")]
        public string Email { get; set; }
    }
}
